ARG ROS_IMAGE=ros:jazzy-ros-base-noble@sha256:31daab66eef9139933379fb67159449944f4e2dcf2e22c2d12cc715f29873e0f
FROM ${ROS_IMAGE}

SHELL ["/bin/bash", "-c"]

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git \
        python3-colcon-common-extensions \
        python3-matplotlib \
        python3-numpy \
        python3-pytest \
        python3-scipy \
        ros-jazzy-ament-copyright \
        ros-jazzy-ament-flake8 \
        ros-jazzy-ament-lint-auto \
        ros-jazzy-ament-lint-common \
        ros-jazzy-ament-pep257 \
        ros-jazzy-launch-testing \
        ros-jazzy-launch-testing-ros \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
COPY . /work

CMD ["bash", "scripts/validate_ros2_010.sh"]
